scraping:
  domain: "https://www.youtube.com"
  max_videos: 10
  query_fallback: "shorts"
  user_agents:
    - Mozilla/5.0 (X11; Linux x86_64)
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64)
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
  delay:
    min: 2
    max: 6
fallback:
  yt_dlp: true